FROM python:3.10.4-alpine3.14

WORKDIR /app


# Install pip dependencies
COPY app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy all the backend code
COPY . .

# Activate the venv
ENV PATH="/app/website-monitor-app/venv/bin:$PATH"

# Expose the port the app runs on
EXPOSE 8000

# Command to run on container start
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
